server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-preference-service
          uri: lb://user-preference-service
          predicates:
            - Path=/api/preferences/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        - id: news-service
          uri: lb://notification-service
          predicates:
            - Path=/api/news/**
          filters:
            - StripPrefix=1
        - id: telegram-webhook
          uri: lb://notification-service
          predicates:
            - Path=/telegram/**
        - id: scraper-service
          uri: lb://scraper-service
          predicates:
            - Path=/api/scraper/**
          filters:
            - StripPrefix=1
        - id: admin-notifications-stats
          uri: lb://notification-service
          predicates:
            - Path=/api/admin/notifications/**
          filters:
            - RewritePath=/api/admin/notifications/(?<segment>.*), /admin/$\{segment}
        - id: admin-users-stats
          uri: lb://user-preference-service
          predicates:
            - Path=/api/admin/users/**
          filters:
            - RewritePath=/api/admin/users/(?<segment>.*), /admin/$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
